[project]
name = "periodic-sentence-bot"
version = "0.0.1"
requires-python = ">= 3.12"
dependencies = [
    "disnake >=2.9.1",
    "Flask >=3.0.3",
    "python-dotenv >=1.0.1",
]

[tool.uv]
package = false
